name: Build and Test

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Test using ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
           python -m pip install pip --upgrade pip
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
           curl -L -o src/database/database.zip https://www.dropbox.com/s/co34arck1nbgfzb/database.zip?dl=0
           unzip -o src/database/database.zip
           rm src/database/database.zip

      - name: run unit tests [pytest] 
        run: |
            export PYTHONPATH=src
            pytest
