name: Build and Test

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Test using ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6

      - name: Install Dependencies
        run: |
           python -m pip install pip --upgrade pip
           sudo apt-get install libsqlite3-dev
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
           cd src/database/
           curl -L -o database.zip ${{ secrets.DB_URL }}
           unzip -o database.zip
           rm database.zip
           cd ../..
           cd src/scripts/
           curl -L -o secret.py ${{ secrets.SECRET_URL }}
           cd ../..
           echo $(pwd)
           echo $(ls src/database/)

      - name: run unit tests [pytest] 
        run: |
            export PYTHONPATH=src
            pytest
